%import common.NUMBER
int: NUMBER

?offset : ("+" int) -> p_offset
        | ("-" int) -> n_offset

%import common.CNAME
ident: CNAME

%import common.WS
%ignore WS

%import common.SH_COMMENT
%ignore SH_COMMENT

stmt_add : "add" int

stmt_zero: "zero"

stmt_move: "move" offset

%import common.ESCAPED_STRING
stmt_raw: "raw" ESCAPED_STRING

?stmt_: stmt_add
      | stmt_zero
      | stmt_move
      | stmt_raw
_stmt: stmt_ ";"

_line: _stmt
     | "\n"

program: (_line "\n"*)* "\n"?